export interface Morpheme { surface: string; pos: PosTag; base_form: string; reading: string; conjugation_type: string; conjugation_form: string; char_range: [number, number]; }
export interface PosTag { major: string; sub1: string; sub2: string; sub3: string; }
export interface GrammarTag { pattern_id: string; name_ja: string; name_en: string; jlpt_level: number | null; description: string; morpheme_range: [number, number]; char_range: [number, number]; }
export interface WordFormationCapture { name: string; surface: string; morpheme_range: [number, number]; char_range: [number, number]; }
export interface WordFormationAnnotation { rule_id: string; category: string; surface: string; base_form: string; reading: string; output_pos: PosTag; morpheme_range: [number, number]; char_range: [number, number]; head_morpheme: number; captures: WordFormationCapture[]; confidence: number; }
export type BunsetsuFunction = "predicate" | "case_phrase" | "adnominal" | "adverbial" | "conjunctive" | "nominal" | "standalone" | "unknown";
export interface BunsetsuFunctionAnnotation { function: BunsetsuFunction; confidence: number; evidence: string[]; syntax_evidence: string[]; }
export interface HeadWord { surface: string; base_form: string; reading: string; pos: PosTag; }
export interface Bunsetsu { morphemes: Morpheme[]; surface: string; head_word: HeadWord; grammar_tags: GrammarTag[]; word_formations: WordFormationAnnotation[]; function?: BunsetsuFunctionAnnotation | null; char_range: [number, number]; }
export type ExpressionType = "lexical_unit" | "idiom" | "grammar_construction" | "correlative";
export type ExpressionBoundaryEffect = "merge_lexical_unit" | "regroup_bunsetsu" | "annotate_only";
export interface ExpressionPatternPart { lemmas: string[]; pos: string[]; pos_details: PosTag[]; conjugation_types: string[]; conjugation_forms: string[]; surface_hint: string; is_slot: boolean; alignment?: "full" | "suffix" | "prefix"; is_any?: boolean; }
export interface ExpressionRule { id: number; schema_version: number; rule_version: number; enabled: boolean; requires_review: boolean; label: string; description: string; origin: string; expression_type: ExpressionType; priority: number; boundary_effect: ExpressionBoundaryEffect; parts: ExpressionPatternPart[]; created_at: string; gap_after?: number; gap_bunsetsu?: [number, number]; }
export interface ExpressionAnnotation { match_id: string; rule_id: number; label: string; description: string; origin: string; expression_type: ExpressionType; priority: number; boundary_effect: ExpressionBoundaryEffect; confidence: number; position: "start" | "middle" | "end" | "single"; token_range: [number, number]; char_range: [number, number]; matched_ranges: [number, number][]; surface: string; }
export interface ExpressionRulePreview { status: "accepted" | "pending" | "rejected"; expression_type: ExpressionType; surface: string; matched_ranges: [number, number][]; covered_token_range: [number, number]; evidence: string[]; counter_evidence: string[]; rejection_reason: string | null; }
export interface AnnotatedToken { bunsetsu: Bunsetsu; novelty_score: number; is_selected: boolean; is_known: boolean; inference_reason: string | null; expressions: ExpressionAnnotation[]; display_class: "content" | "punctuation" | "line_break"; }
export interface SegmentationCandidate { tokens: AnnotatedToken[]; total_cost: number; relative_cost: number; source: "vibrato_lattice"; vibrato_rank: number; rank_score: number; dictionary_evidence: string[]; }
export interface DictionaryLink { target: string; label: string; relation: "candidate" | "redirect" | "synonym" | "antonym" | "parent" | "child" | "phrase" | "reference" | "related"; }
export interface DictionaryContentBlock { kind: "rich_text" | "notice" | string; label: string | null; html: string; }
export interface DictionaryChoiceOption { key: string; label: string; active: boolean; preferred?: boolean; title?: string; }
export interface DictEntry { entry_key: string; dict_name: string; headword: string; reading: string | null; is_preferred: boolean; definition_html: string; style_profile: string; content_blocks: DictionaryContentBlock[]; match_type: "headword" | "reading" | "fuzzy"; links: DictionaryLink[]; }
export interface DictionaryLookup { query: string; reading: string | null; selected_target: string | null; candidates: DictionaryLink[]; entries: DictEntry[]; }
export interface ExportEntry { surface: string; base_form: string; reading: string; pos: string; grammar_tags: string[]; jlpt_levels: number[]; context_sentence: string; context_highlight: [number, number]; definitions: DictEntry[]; user_note: string; char_range?: [number, number]; }
