//! UniDic 分析对象与来源适配。
pub mod model;
pub mod prepare;
pub mod routing;
mod ruby;
pub mod sources;
pub mod unify;
pub mod structure;
pub mod syntax;
pub mod formation;
pub mod bunsetsu;
pub mod alignment;
pub mod clause;
pub mod lexical;
pub mod grammar;
pub mod expression;
pub mod projection;
pub mod morphology;
pub mod native;
