import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const output = '.agents/unidic-ui';
await mkdir(output, { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(process.env.KOTOCLIP_TEST_URL || 'http://127.0.0.1:1420', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.getByRole('button', { name: '分析', exact: true }).click();
  await page.getByRole('button', { name: '警察', exact: true }).waitFor({ timeout: 60000 });
  await page.getByRole('button', { name: '警察', exact: true }).click();
  await page.locator('.entry').first().waitFor({ timeout: 30000 });
  assert.match(await page.locator('.query-reading').innerText(), /ケイサツ/);
  await page.screenshot({ path: `${output}/desktop-query.png`, fullPage: true });
  await page.getByRole('tab', { name: 'UniDic 元数据' }).click();
  assert.equal(await page.locator('.metadata-table tbody tr').count(), 29);
  assert.match(await page.locator('.metadata-table').innerText(), /ケーサツ/);
  await page.screenshot({ path: `${output}/desktop-metadata.png`, fullPage: true });
  await page.getByRole('button', { name: '向かっ', exact: true }).click();
  await page.getByRole('tab', { name: '词典', exact: true }).click();
  await page.locator('.entry').first().waitFor({ timeout: 30000 });
  assert.match(await page.locator('.query-forms').innerText(), /向かう/);
  await page.getByRole('button', { name: '口语 CSJ', exact: true }).click();
  await page.getByRole('textbox', { name: '日文正文' }).fill('何か用があったのですか？\n𠮷野は云う。');
  await page.getByRole('button', { name: '分析', exact: true }).click();
  await page.locator('.token-text').waitFor({ timeout: 60000 });
  assert.equal(await page.locator('.token-text').innerText(), '何か用があったのですか？\n𠮷野は云う。');
  assert.match(await page.locator('.result-toolbar').innerText(), /csj/);
  await page.getByRole('button', { name: '云う', exact: true }).click();
  await page.locator('.entry').first().waitFor({ timeout: 30000 });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${output}/mobile-query.png`, fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('tab', { name: 'UniDic 元数据' }).click();
  await page.screenshot({ path: `${output}/mobile-metadata.png`, fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('tab', { name: '词典', exact: true }).click();
  await page.getByRole('textbox', { name: '查询词', exact: true }).fill('zzzznotaword');
  await page.getByRole('button', { name: '查询', exact: true }).click();
  await page.getByText('未找到词条', { exact: true }).waitFor({ timeout: 30000 });
  const image = await page.locator('.brand img').evaluate(img => img.complete && img.naturalWidth > 0);
  assert.ok(image);
  assert.deepEqual(errors, []);
  console.log('通过：双词典分析、原文坐标、逐词查询、29 列元数据、无命中状态、桌面与窄屏布局。');
} finally { await browser.close(); }
